- name: cleanup controller process
  hosts: {{ ctrl_host }}
  gather_facts: false
  become: false
  tasks:
    - name: kill controller process
      shell: "pkill -f 'python -m infscale start controller'"
      ignore_errors: true

    - name: Kill GPU-using Python processes belonging to current user
      shell: |
        USERNAME=$(whoami)
        GPU_PIDS=$(nvidia-smi | grep python | awk '{print $5}')
        USER_PIDS=$(ps -u $USERNAME -o pid=)
        for pid in $GPU_PIDS; do
          if echo "$USER_PIDS" | grep -wq "$pid"; then
            kill "$pid"
          fi
        done

- name: cleanup agent processes and remove tmp log files
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - name: Remove tmp_logs directory and its contents
      shell: "rm -rf {{ log_folder }}"
      ignore_errors: true

    - name: kill agent processes
      shell: "pkill -f 'python -m infscale start agent'"
      ignore_errors: true
