# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from infscale.openapi.models.http_validation_error import HTTPValidationError
from infscale.openapi.models.response import Response
from infscale.openapi.models.serve_spec import ServeSpec
from infscale.openapi.models.validation_error import ValidationError
from infscale.openapi.models.validation_error_loc_inner import ValidationErrorLocInner
