from infscale.configs.job import JobConfig, WorkerData

remove_pipeline_test_cases = [
    # Test case 1: two pipelines, first layer failed worker
    (
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
                WorkerData(id="2-0", stage={}, device="cpu"),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}, {"name": "w7", "peers": ["2-1"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}],
                "2-0": [{"name": "w3", "peers": ["1-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"0-0"},
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w7", "peers": ["2-1"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
            },
        ),
    ),
    # Test case 2 two pipelines, last layer failed worker
    (
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
                WorkerData(id="2-0", stage={}, device="cpu"),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}, {"name": "w7", "peers": ["2-1"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}],
                "2-0": [{"name": "w3", "peers": ["1-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"2-0"},
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w7", "peers": ["2-1"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
            },
        ),
    ),
        # Test case 3 two pipelines, mid layer failed worker
    (
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
                WorkerData(id="2-0", stage={}, device="cpu"),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}, {"name": "w7", "peers": ["2-1"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}],
                "2-0": [{"name": "w3", "peers": ["1-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-0"},
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w7", "peers": ["2-1"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
            },
        ),
    ),
    # Test case 4: diamond, replica fails
    (
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["1-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}, {"name": "w3", "peers": ["0-1"]}],
            },
        ),
        {"0-0"},
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["1-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-1"]}],
            },
        ),
    ),
    # Test case 5: llama, 0-0 fails
    (
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
                WorkerData(id="2-0", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}, {"name": "w2", "peers": ["2-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "2-0": [{"name": "w4", "peers": ["1-0"]}],
            },
        ),
        {"0-0"},
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [],
            },
        ),
    ),
    # Test case 6: 3 pipelines, 2 failed workers
    (
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
                WorkerData(id="2-0", stage={}, device="cpu"),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
                WorkerData(id="0-2", stage={}, device="cpu"),
                WorkerData(id="1-2", stage={}, device="cpu"),
                WorkerData(id="2-2", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}, {"name": "w7", "peers": ["2-1"]}, {"name": "w11", "peers": ["2-2"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}],
                "2-0": [{"name": "w3", "peers": ["1-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
                "0-2": [{"name": "w8", "peers": ["s-0"]}],
                "1-2": [{"name": "w9", "peers": ["0-2"]}],
                "2-2": [{"name": "w10", "peers": ["1-2"]}],
            },
        ),
        {"0-0", "0-2"},
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w7", "peers": ["2-1"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
            },
        ),
    ),
    # Test case 7: 3 pipelines, 2 failed workers, one second layer, one third layer
    (
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
                WorkerData(id="2-0", stage={}, device="cpu"),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
                WorkerData(id="0-2", stage={}, device="cpu"),
                WorkerData(id="1-2", stage={}, device="cpu"),
                WorkerData(id="2-2", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}, {"name": "w7", "peers": ["2-1"]}, {"name": "w11", "peers": ["2-2"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}],
                "2-0": [{"name": "w3", "peers": ["1-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
                "0-2": [{"name": "w8", "peers": ["s-0"]}],
                "1-2": [{"name": "w9", "peers": ["0-2"]}],
                "2-2": [{"name": "w10", "peers": ["1-2"]}],
            },
        ),
        {"1-1", "2-2"},
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
                WorkerData(id="2-0", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}],
                "2-0": [{"name": "w3", "peers": ["1-0"]}],
            },
        ),
    ),
    # Test case 8: 3 pipelines, 2 failed workers in the same pipeline
    (
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-0", stage={}, device="cpu"),
                WorkerData(id="1-0", stage={}, device="cpu"),
                WorkerData(id="2-0", stage={}, device="cpu"),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
                WorkerData(id="0-2", stage={}, device="cpu"),
                WorkerData(id="1-2", stage={}, device="cpu"),
                WorkerData(id="2-2", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}, {"name": "w7", "peers": ["2-1"]}, {"name": "w11", "peers": ["2-2"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}],
                "2-0": [{"name": "w3", "peers": ["1-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
                "0-2": [{"name": "w8", "peers": ["s-0"]}],
                "1-2": [{"name": "w9", "peers": ["0-2"]}],
                "2-2": [{"name": "w10", "peers": ["1-2"]}],
            },
        ),
        {"1-2", "0-2"},
        JobConfig(
            job_id="job1",
            workers=[
                WorkerData(id="s-0", stage={}, device="cpu", is_server=True),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
                WorkerData(id="0-1", stage={}, device="cpu"),
                WorkerData(id="1-1", stage={}, device="cpu"),
                WorkerData(id="2-1", stage={}, device="cpu"),
            ],
            name="test",
            model="model",
            dataset=None,
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}, {"name": "w7", "peers": ["2-1"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "1-0": [{"name": "w2", "peers": ["0-0"]}],
                "2-0": [{"name": "w3", "peers": ["1-0"]}],
                "0-1": [{"name": "w4", "peers": ["s-0"]}],
                "1-1": [{"name": "w5", "peers": ["0-1"]}],
                "2-1": [{"name": "w6", "peers": ["1-1"]}],
            },
        ),
    ),
]
